;; -*- mode: eask; lexical-binding: t -*-

(package "org-kanban" "0.6.16" "Kanban dynamic block for org-mode")
(website-url "https://github.com/gizmomogwai/org-kanban")
(keywords "org" "org-mode" "kanban" "tools")

(package-file "org-kanban.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "31.1")
(depends-on "dash")
(depends-on "s")
(development
 (depends-on "ert-runner")
 (depends-on "undercover")
 (depends-on "ert-expectations")
 (depends-on "ecukes")
 (depends-on "espuds"))
