* Kanban dynamic block for org-mode
[[https://travis-ci.org/gizmomogwai/org-kanban][https://img.shields.io/travis/gizmomogwai/org-kanban/master.svg?style=flat-square]]
[[https://melpa.org/#/org-kanban][https://melpa.org/packages/org-kanban-badge.svg]]

Inspired by some of the kanban resources for emacs out there ([[http://www.agilesoc.com/2011/08/08/emacs-org-mode-kanban-pomodoro-oh-my/][Emacs,
org-mode, Kanban, Pomodoro… Oh my…]], or [[http://www.draketo.de/files/kanban.el][kanban.el]]), I came
up with this solution.


** Solution
It uses a custom org-mode dynamic block and provides some operations
on the table rows.


** Beware
org-kanban only works in org-buffers that have an underlying file.

If you wonder why your kanban board looks the wrong way around, please
have a look [[https://theagileist.wordpress.com/tag/mirrored-kanban-board/][here]]. If you do not like this behavior, just
remove :mirrored t or set it to nil.
You can use =org-kanban/shift= on a row, to move the TODO one keyword
back or forth.


** Walkthrough (see [[https://asciinema.org/a/201532][asciinema]])
- Open an org file with some todos e.g. org-kanban-demo.org
- Move through all todos


** TL;TR
- Open an org file and call `org-kanban/initialize-at-end`


** Test the package
The quickest way to test the package in isolation is to run

#+BEGIN_SRC shell
docker run -it --rm alpine:latest /bin/sh
apk update
apk add emacs
emacs
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-list)
search for org-kanban and press i
#+END_SRC
